Catalog Services with exception handling
eklavya/activeGrid pull request #10
Opened 2016-10-12 09:41 UTC by naveed050

2016-10-13 06:56 UTC, eklavya requested changes

2016-10-13 06:56 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +    withTx { neo =>
There has to be a consistency in formatting. Don't insert newlines at will.

2016-10-13 06:56 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +
Don't submit PR next time unless you have formatted your code.

2016-10-13 06:56 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +      println(s" new node ${node.getLabels}, id ${node.getId}")
No printlns.

2016-10-13 06:56 UTC, eklavya commented on src/main/scala/com/activegrid/model/StorageInfo.scala
> +      val mapPrimitives : Map[String, Any] = Map("used" -> entity.used, "total" -> entity.total)
No type annotations needed here.

2016-10-13 11:07 UTC, naveed050 commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +    withTx { neo =>
removed extra lines

2016-10-13 11:07 UTC, naveed050 commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +      println(s" new node ${node.getLabels}, id ${node.getId}")
used logger instead of printlns

2016-10-13 11:08 UTC, naveed050 commented on src/main/scala/com/activegrid/model/StorageInfo.scala
> +      val mapPrimitives : Map[String, Any] = Map("used" -> entity.used, "total" -> entity.total)
removed type annotations

2016-10-19 06:10 UTC, eklavya requested changes

2016-10-19 06:10 UTC, eklavya commented on src/main/scala/com/activegrid/model/KeyPairInfo.scala
> +        val keyName = propertyValues.get("keyName").get.toString
You are calling get on a lot of Options. Are you sure there won't be any None here?

2016-10-19 06:10 UTC, eklavya commented on src/main/scala/com/activegrid/model/Tuple.scala
> +case class Tuple(override val id: Option[Long],key: String, value: String)  extends BaseEntity
It can have a more informative name than Tuple.

2016-10-19 06:10 UTC, eklavya commented on src/main/scala/com/activegrid/services/CatalogService.scala
> +class CatalogService(implicit val executionContext: ExecutionContext){
Why is this a class? Are you expecting more than one objects for it? Why is it taking executionContext as an argument?

2016-10-19 06:10 UTC, eklavya commented on src/main/scala/com/activegrid/model/Graph.scala
> +    def fromNeo4jGraph(id: Option[Long]): Option[T]
Why is id optional?

2016-10-19 06:10 UTC, eklavya commented on src/main/scala/com/activegrid/model/InstanceConnection.scala
> +      InstanceConnection.fromNeo4jGraph(id)
It should be id.map(InstanceConnection.fromNeo4jGraph)

2016-10-19 06:33 UTC, naveed050 commented on src/main/scala/com/activegrid/model/Graph.scala
> +    def fromNeo4jGraph(id: Option[Long]): Option[T]
For entities within entities, if inner entity is optional while persisting, we get may or may not get child id while converting it to case class.

So I am passing this Optional id directly to fromNeo4jGraph, which will take care of handling this situation

2016-10-19 06:35 UTC, naveed050 commented on src/main/scala/com/activegrid/services/CatalogService.scala
> +class CatalogService(implicit val executionContext: ExecutionContext){
Removed Service Layer

2016-10-19 06:40 UTC, naveed050 commented on src/main/scala/com/activegrid/model/KeyPairInfo.scala
> +        val keyName = propertyValues.get("keyName").get.toString
Yes Saurabh, there wont be any None

2016-10-19 06:42 UTC, naveed050 commented on src/main/scala/com/activegrid/model/InstanceConnection.scala
> +      InstanceConnection.fromNeo4jGraph(id)
Could you please explain the advantage of using it

2016-10-19 06:44 UTC, naveed050 commented on src/main/scala/com/activegrid/model/KeyPairInfo.scala
> +        val keyName = propertyValues.get("keyName").get.toString
Also we changed it to propertyValues("keyName").toString

2016-10-19 06:46 UTC, naveed050 commented on src/main/scala/com/activegrid/model/Tuple.scala
> +case class Tuple(override val id: Option[Long],key: String, value: String)  extends BaseEntity
Tuple was the name used in java code. Can I change it to KeyValueInfo

2016-10-24 09:35 UTC, merged