App setting service
eklavya/activeGrid pull request #11
Opened 2016-10-12 10:32 UTC by nagulmeeras

It is contains service endpoints to to save/update/delete application level and authentication level settings. updating application logger configuration can also be part of this service.

2016-10-13 06:52 UTC, eklavya requested changes

2016-10-13 06:52 UTC, eklavya commented on src/main/scala/com/activegrid/Main.scala
> +  val appSettingService : AppSettingService = new AppSettingService
No need for this.

2016-10-13 06:52 UTC, eklavya commented on src/main/scala/com/activegrid/utilities/Connection.scala
> +  def getConnection(): Driver ={
Since the driver will be shared by the whole app, don't create a method for it. Just initialise it as a val.

2016-10-18 13:07 UTC, nagulmeeras commented on src/main/scala/com/activegrid/Main.scala
> +  val appSettingService : AppSettingService = new AppSettingService
Removed and updated

2016-10-18 13:08 UTC, nagulmeeras commented on src/main/scala/com/activegrid/utilities/Connection.scala
> +  def getConnection(): Driver ={
Removed

2016-10-19 09:10 UTC, eklavya requested changes

2016-10-19 09:10 UTC, eklavya commented on src/main/scala/com/activegrid/models/APMProvider.scala
> +    println(provider)
no printlns

2016-10-19 09:10 UTC, eklavya commented on src/main/scala/com/activegrid/Main.scala
> +      }
```scala
val appSettings = Future {
  AppSetttings.getAppSettingNode().flatMap(node =>AppSettings.fromNeo4jGraph(node.getId))
}
```

2016-10-19 09:10 UTC, eklavya commented on src/main/scala/com/activegrid/models/APMServerDetails.scala
> +    override def toNeo4jGraph(): Option[Node] = {
Why does this return an Option? You are always getting a Some(node).

2016-10-19 09:10 UTC, eklavya commented on src/main/scala/com/activegrid/models/AppSettings.scala
> +      val node = getAppSettingNode()
getAppSettingNode.map { node =>
}

2016-10-19 09:10 UTC, eklavya commented on src/main/scala/com/activegrid/models/AppSettings.scala
> +          Some(nodes.head)
nodes.headOption

2016-10-19 13:46 UTC, nagulmeeras commented on src/main/scala/com/activegrid/models/APMProvider.scala
> +    println(provider)
Removed printlns

2016-10-19 13:47 UTC, nagulmeeras commented on src/main/scala/com/activegrid/Main.scala
> +      }
Used flatMap in places wherever it is possible

2016-10-19 13:49 UTC, nagulmeeras commented on src/main/scala/com/activegrid/models/APMServerDetails.scala
> +    override def toNeo4jGraph(): Option[Node] = {
Changed Option[Node] to Node now

2016-10-19 13:52 UTC, nagulmeeras commented on src/main/scala/com/activegrid/models/AppSettings.scala
> +      val node = getAppSettingNode()
Changed code as above snippet

2016-10-19 13:52 UTC, nagulmeeras commented on src/main/scala/com/activegrid/models/AppSettings.scala
> +          Some(nodes.head)
Updated as above

2016-10-24 07:12 UTC, merged