Catalog Service Apis with exception handling
eklavya/activeGrid pull request #12
Opened 2016-10-12 10:59 UTC by srachakonda

2016-10-13 06:48 UTC, eklavya requested changes

2016-10-13 06:48 UTC, eklavya commented on build.sbt
> +  val Json4sVersion     = "3.2.11"
Remove unused dependency.

2016-10-13 06:48 UTC, eklavya commented on src/main/scala/com/activegrid/Main.scala
> +            case util.Failure(exception) => complete(StatusCodes.BadRequest, "Unable to Retrieve ImageInfo List. Failed with " + exception)
Log exceptions. Use string interpolation instead of using '+' wherever needed.

2016-10-13 06:48 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +      println(s" (${key}) --> (${node.getProperty(key)}) ")
No printlns.

2016-10-18 10:58 UTC, eklavya requested changes

2016-10-18 10:58 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +  def getProperties(node: Node, keys: String*): Map[String, Any] = withTx { neo =>
Why Map of Any?

2016-10-18 10:58 UTC, eklavya commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +      node.setProperty("", "")
Why do we need this?

2016-10-18 10:58 UTC, eklavya commented on src/main/scala/com/activegrid/model/Software.scala
> +      map.get("name").get.asInstanceOf[String],
map.get(x).get is same as map(x)

2016-10-18 11:21 UTC, srachakonda commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +  def getProperties(node: Node, keys: String*): Map[String, Any] = withTx { neo =>
As the value can be either String or any right.

2016-10-18 11:22 UTC, srachakonda commented on src/main/scala/com/activegrid/model/GraphDBExecutor.scala
> +      node.setProperty("", "")
Need to remove it used it earlier now I am not using it and thought of keeping it as placeholder but will remove unused methods

2016-10-18 11:23 UTC, srachakonda commented on src/main/scala/com/activegrid/model/Software.scala
> +      map.get("name").get.asInstanceOf[String],
ok cool will change it

2016-10-19 09:01 UTC, eklavya commented on src/main/scala/com/activegrid/model/Software.scala
> +      case exception: Exception => throw new Exception("Unable to get the Entity")
don't throw, log it

2016-10-19 09:50 UTC, srachakonda commented on src/main/scala/com/activegrid/model/Software.scala
> +      case exception: Exception => throw new Exception("Unable to get the Entity")
Hi Saurabh I am handling it in Controller

2016-10-19 11:26 UTC, eklavya commented on src/main/scala/com/activegrid/utils/ActiveGridUtils.scala
> +    map.get(key) match {
```scala
map.get(key).map(_.asInstanceOf[T])
```

2016-10-19 11:27 UTC, eklavya commented on src/main/scala/com/activegrid/model/Software.scala
> +      case exception: Exception => throw new Exception("Unable to get the Entity")
Just don't catch the exception and the caller will log the original exception with proper stack trace.

2016-10-21 09:44 UTC, eklavya commented on src/main/scala/com/activegrid/model/Software.scala
> +      case nse: NoSuchElementException =>
There is no special handling of NoSuchElementException so remove this case.

2016-10-21 12:00 UTC, merged