UserSerice
eklavya/activeGrid pull request #13
Opened 2016-10-12 11:53 UTC by babjikundateeri

With exception handling

2016-10-13 06:44 UTC, eklavya requested changes

2016-10-13 06:44 UTC, eklavya commented on build.sbt
> +  val Json4sVersion     = "3.2.11"
Remove unused dependency

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/Main.scala
> +  implicit val neo4jRepository = Neo4jRepository
Why is this implicit? Why are you creating a val for this at all?

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
> +      val map: Map[String, Any] = Map()
use Map.empty[String, Any]

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
> +      ImageInfo(Some(0L), "", "", "", false, "", "", "", "", "", "", "", "", "")
What's going on here?

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/KeyPairInfo.scala
> +    new KeyPairInfo(None, keyName, Some(""), keyMaterial, filePath, status, Some(""), Some(""))
Why Some(""), why not None?

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/KeyPairStatus.scala
> +object KeyPairStatus extends Enumeration {
Do not use Enumeration, use a sealed trait/class.

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRep.scala
> +  def toNeo4jGraph(entity: T): Option[Node] = ???
Why are you providing a default implementation that is ???

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +    val node = getOrSaveEntity(label, id)
fix formatting

2016-10-13 06:44 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Permission.scala
> +object Permission extends Enumeration {
Don't use Enumeration.

2016-10-13 09:58 UTC, babjikundateeri commented on build.sbt
> +  val Json4sVersion     = "3.2.11"
Removed all unused imports

2016-10-13 09:59 UTC, babjikundateeri commented on src/main/scala/com/imaginea/Main.scala
> +  implicit val neo4jRepository = Neo4jRepository
Removed this unused statement

2016-10-13 10:00 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
> +      val map: Map[String, Any] = Map()
This part of code is belongs to ImageInfo, which is handled by sampth,
i removed it from my repository

2016-10-13 10:00 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
> +      ImageInfo(Some(0L), "", "", "", false, "", "", "", "", "", "", "", "", "")
This part of code is belongs to ImageInfo, which is handled by sampth,
i removed it from my repository

2016-10-13 10:01 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/KeyPairInfo.scala
> +    new KeyPairInfo(None, keyName, Some(""), keyMaterial, filePath, status, Some(""), Some(""))
now i am using None instead of Some("")

2016-10-13 10:02 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRep.scala
> +  def toNeo4jGraph(entity: T): Option[Node] = ???
removed default implementation with ???

2016-10-13 10:02 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +    val node = getOrSaveEntity(label, id)
reformatted code

2016-10-17 06:58 UTC, eklavya requested changes

2016-10-17 06:58 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +    nodesIterator.size match {
use nodesIterator.headOption

2016-10-17 06:58 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +  def findNodeById(id: Long): Option[Node] = withTx { implicit neo =>
Option already implies Node might not be there, why are we throwing instead of using None?

2016-10-17 06:58 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +  def findNodeByLabelAndId(label: String, id: Long): Option[Node] = withTx { implicit neo =>
Same thing here.

2016-10-18 04:00 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +    nodesIterator.size match {
changed code to use headOption

2016-10-18 04:01 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +  def findNodeById(id: Long): Option[Node] = withTx { implicit neo =>
Removed Option as throwing exception

2016-10-18 04:01 UTC, babjikundateeri commented on src/main/scala/com/imaginea/activegrid/core/models/Neo4jRepository.scala
> +  def findNodeByLabelAndId(label: String, id: Long): Option[Node] = withTx { implicit neo =>
Removed Option as throwing exception

2016-10-21 09:42 UTC, merged