Discovery service
eklavya/activeGrid pull request #17
Opened 2016-10-28 11:26 UTC by naveed050

added code to create Instance from AWSInstance for discoveryService route
added  custom write for jsonFormat of Instance as it has more than 22 fields. did not write custom read

2016-10-28 13:09 UTC, eklavya requested changes

2016-10-28 13:09 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
>  case class ImageInfo(override val id: Option[Long],
Even the id is optional?

2016-10-28 13:09 UTC, eklavya commented on src/main/scala/com/imaginea/Main.scala
> +      val fieldName1 = "id"
This could definitely be more terse. Why are we doing it in the max lines possible way?

2016-10-31 04:27 UTC, naveed050 commented on src/main/scala/com/imaginea/activegrid/core/models/ImageInfo.scala
>  case class ImageInfo(override val id: Option[Long],
id is optional in all case classes as we assign the value to it  after getting the id by saving it to graph db

2016-10-31 05:18 UTC, naveed050 commented on src/main/scala/com/imaginea/Main.scala
> +      val fieldName1 = "id"
I will look into it

2016-11-03 06:04 UTC, eklavya commented on src/main/scala/com/imaginea/Main.scala
> +      fields ++= longToJsField(fieldNames(1), i.id)
Why can't you just do:
```scala
JsObject(
  "id" -> i.id,
  ...
)
```

2016-11-03 06:05 UTC, eklavya commented on src/main/scala/com/imaginea/activegrid/core/models/AWSComputeAPI.scala
> +      import scala.collection.JavaConversions._
Why not import at the top?

2016-11-03 06:09 UTC, naveed050 commented on src/main/scala/com/imaginea/Main.scala
> +      fields ++= longToJsField(fieldNames(1), i.id)
id is optional (along with other fields)  , so we need to check first if there is some value or not. Only then we are adding it to JsObject

2016-11-03 06:11 UTC, naveed050 commented on src/main/scala/com/imaginea/activegrid/core/models/AWSComputeAPI.scala
> +      import scala.collection.JavaConversions._
Yes Saurabh, removed it now

2016-11-03 09:47 UTC, merged