Application settings service
eklavya/activeGrid pull request #8
Opened 2016-10-07 13:29 UTC by sivakumargollu

Simple design for app-setting service  with classes and objects
Contains service endpoints to manage application-settings and authentication information. It also contains logger config  endpoints.

2016-10-13 07:00 UTC, eklavya requested changes

2016-10-13 07:00 UTC, eklavya commented on .gitignore
> +*.iws
This doesn't make any sense. Use what others are using.

2016-10-13 07:00 UTC, eklavya commented on src/main/scala/com/activegrid/models/LogConfigUpdater.scala
> +  def getLogger(logger: String): Logger = {
What is this?

2016-10-13 07:00 UTC, eklavya commented on src/main/scala/com/activegrid/models/LogConfigUpdater.scala
> +  def getLogLevel2(logger: String): Future[String] = Future {
Why do we need all this?

2016-10-13 07:00 UTC, eklavya commented on src/main/scala/com/activegrid/neo4j/AppSettingsNeo4jWrapper.scala
> +          for (n <- settingNodes) {
What is this?

2016-10-13 07:00 UTC, eklavya commented on src/main/scala/com/activegrid/neo4j/AppSettingsNeo4jWrapper.scala
> +          for (n <- settingNodes) {
What is this?

2016-10-17 10:35 UTC, sivakumargollu commented on src/main/scala/com/activegrid/neo4j/AppSettingsNeo4jWrapper.scala
> +          for (n <- settingNodes) {
String  "AS" is key to the value "AppSettings" label defined in the "labels" which is map.

2016-10-17 10:37 UTC, sivakumargollu commented on src/main/scala/com/activegrid/models/LogConfigUpdater.scala
> +  def getLogLevel2(logger: String): Future[String] = Future {
We have end points that return back  LOGGER related information. We couldn't find any use case but might required by other services. Now corrected the method definition.

2016-10-17 10:37 UTC, sivakumargollu commented on src/main/scala/com/activegrid/models/LogConfigUpdater.scala
> +  def getLogger(logger: String): Logger = {
Method definition corrected

2016-10-17 10:38 UTC, sivakumargollu commented on .gitignore
> +*.iws
.ipr and .iws are the intellej auto-generated files which contains project files related information. To make it simple and clean, except source files remaining all are excluded and also unused statements from .gitigore removed.

2016-10-19 11:33 UTC, eklavya commented on src/main/scala/com/activegrid/neo4j/AppSettingsNeo4jWrapper.scala
> +  def updateSettings(settingsMap: Map[String, String], relationName: String): String = {
Why are you creating a string of success and failure?

2016-10-19 11:52 UTC, sivakumargollu commented on src/main/scala/com/activegrid/neo4j/AppSettingsNeo4jWrapper.scala
> +  def updateSettings(settingsMap: Map[String, String], relationName: String): String = {
I had created string to   use it as STATUS that let the function caller know weather  operation succeeded or not. I changed this just committed code please review it

2016-10-24 12:59 UTC, merged